### ISSUE TITLE
RentCar 프로젝트 - 기획 : SQL과 visual studio C#의 구성.

### ISSUE THREAD

**Issue by KimHuiEun** [KimHuiEun/RentCar#1]
DB

-서버 : kimpro
-파일명 : RentCar
-테이블명 규칙 : 첫글자대문자, 간결성유지.
   -Rent(Main) ---연결---User, Car
   -User  (= Account)  ---연결---Event
   -Event
   -Car ---연결--- CarType, IsRent의 변수로 렌트중인지아닌지 구분(bit)
   -CarType
   -Admin ---연결--- User, Car
   -Search ---연결--- User, CarType

visual studio C#
-C:git
-솔루션이름 : CarRentalManagementSystem
-프로젝트 이름 : CarRent, CarRent.Data, CarRent.UnitTest
-CarRent의 폼.
  -Login
  -Account
  -Selection
  -Payment
  <<<Mypage>>>>
  -Customer
  -Manager
  -Admin

**Comment by bark-ch** [comment]
https://m.blog.naver.com/jooeun0502/221956294941

**Comment by bark-ch** [comment]
깃헙 Read me 부분 어떻게 작성하는지 블로그 퍼왔어요...~ㅠ
