### ISSUE TITLE
스키마 구현 정리.

### ISSUE THREAD

**Issue by KimHuiEun** [KimHuiEun/RentCar#29]
다시 작성하기 전에 스키마 정리 부탁드릴께요~
1. 결제 테이블이 존재하는지.
2. 고객, 렌트, 직원의 관계가 정확한것인지.

**Comment by bark-ch** [comment]
![paymentdb](https://user-images.githubusercontent.com/74527286/101134865-5b2da880-364e-11eb-97ce-acfb15de2f3d.PNG)
![paymentlinedb](https://user-images.githubusercontent.com/74527286/101134868-5c5ed580-364e-11eb-865b-f21a6c8caba0.PNG)
![relationship](https://user-images.githubusercontent.com/74527286/101134871-5c5ed580-364e-11eb-851b-6ff2012e73fe.PNG)
![rentdb](https://user-images.githubusercontent.com/74527286/101134872-5cf76c00-364e-11eb-82bc-61a1269f30fd.PNG)
![searchdb](https://user-images.githubusercontent.com/74527286/101134874-5cf76c00-364e-11eb-9e1e-2ff16d596114.PNG)
![userdb](https://user-images.githubusercontent.com/74527286/101134875-5d900280-364e-11eb-8122-0bf8b3433b9a.PNG)
![admindb](https://user-images.githubusercontent.com/74527286/101134878-5e289900-364e-11eb-8c95-cd85c53605e3.PNG)
![carinfodb](https://user-images.githubusercontent.com/74527286/101134879-5e289900-364e-11eb-896e-140d2d3eb0f5.PNG)
![carstatedb](https://user-images.githubusercontent.com/74527286/101134882-5ec12f80-364e-11eb-92ea-db7f960ba72f.PNG)

DB와 DB간의 관계 확인, 친욱 베이스를 확인하여 수정할 것들을 수정하였다.
Car와 CarType DB의 명으로 어떤 기능을 하려고 하는지가 명확하지 않아 명칭을 변경하였다.
Car -> CarState
CarType -> CarInfo

**Comment by KimHuiEun** [comment]
이걸 기반으로 폼 구성 다시 해봅시다!
